DROP TABLE IF EXISTS supplier, warehouse, product;

CREATE TABLE IF NOT EXISTS supplier
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sup PRIMARY KEY (id),
    CONSTRAINT uq_sup_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS warehouse
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    address VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_ware PRIMARY KEY (id),
    CONSTRAINT uq_ware_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type          VARCHAR(50)                             NOT NULL,
    sort          VARCHAR(50)                             NOT NULL,
    count         INT                                     NOT NULL,
    price         FLOAT                                   NOT NULL,
    delivery_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ware_id       BIGINT                                  NOT NULL,
    sup_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT fk_sup FOREIGN KEY (sup_id) REFERENCES supplier (id),
    CONSTRAINT fk_ware FOREIGN KEY (ware_id) REFERENCES warehouse (id)
);